apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespaceOverride }}
  name: headscale
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-redirect-from: "http://"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "https://"
    {{ range $key, $val := .Values.ingress.annotations -}}
    {{ $key }}: {{ $val }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{ end -}}
  rules:
    - host: {{ .Values.service.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: headscale
                port:
                  number: 8443
  tls:
    - hosts:
      - {{ .Values.service.host }}
      secretName: headscale-tls
