apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespaceOverride }}
  name: headscale-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "500Mi" .Values.storageSize }}

