apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespaceOverride }}
  name: headscale
{{ if .Values.service.annotations }}
  annotations:
{{- range $key, $val := .Values.service.annotations }}
    {{ $key }}: {{ $val }}
{{ end -}}
{{ end -}}
spec:
  type: LoadBalancer
  ports:
    - name: websecure
      port: {{ .Values.service.externalPort }}
      targetPort: 8443
  selector:
    app: headscale

