apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespaceOverride }}
  name: headscale
  {{- if .Values.service.annotations }}
  annotations:
    {{ range $key, $val := .Values.service.annotations -}}
    {{ $key }}: {{ $val }}
    {{- end }}
  {{- end }}
spec:
  ports:
    - name: websecure
      port: 8443
      targetPort: 8080
  selector:
    app: headscale
