#namespaceOverride: headscale-system

service:
  externalPort: 443
  # host is the hostname that Headscale should respond to from the internet (required)
  # host:
  annotations: {}
    #metallb.universe.tf/address-pool: wan-lb-pool

storageSize: 500Mi

tls:
  secretName: headscale-tls
  clusterIssuer: letsencrypt-dns-prod
