cert-manager:
  crds:
    enabled: true
  dns01RecursiveNameserversOnly: true
  dns01RecursiveNameservers: "8.8.8.8:53,8.8.4.4:53"

dns01:
  awsRegion: us-west-2
  # awsRole: arn:aws:iam::(...) - REQUIRED
  secretName: dns01-creds
  # replyToEmail: someone@somewhere.com - REQUIRED

