apiVersion: v1
kind: ConfigMap
metadata:
  name: address-pool-resources
data:
  resource.yaml: |
    apiVersion: metallb.io/v1beta1
    kind: IPAddressPool
    metadata:
      name: {{ .Values.ipAddressPool.name }}
      namespace: {{ .Values.namespaceOverride }}
      annotations:
        helm.sh/hook: post-install
    spec:
      addresses:
        - {{ required "ipAddressPool.addresses is required" .Values.ipAddressPool.addresses }}
      autoAssign: {{ .Values.ipAddressPool.autoAssign }}
    ---
    apiVersion: metallb.io/v1beta1
    kind: L2Advertisement
    metadata:
      name: pools-advertisement
      namespace: {{ .Values.namespaceOverride }}
      annotations:
        helm.sh/hook: post-install
    spec:
      ipAddressPools:
        - {{ .Values.ipAddressPool.name }}
