apiVersion: v1
kind: ConfigMap
metadata:
  name: address-pool-resources
data:
  resource.yaml: |
    {{ range $item := .Values.ipAddressPools }}
    apiVersion: metallb.io/v1beta1
    kind: IPAddressPool
    metadata:
      name: {{ $item.name }}
      namespace: {{ $.Values.namespaceOverride }}
      annotations:
        helm.sh/hook: post-install
    spec:
      addresses:
        - {{ required "ipAddressPools.addresses is required" $item.addresses }}
      autoAssign: {{ $item.autoAssign }}
    ---
    {{ end -}}
    apiVersion: metallb.io/v1beta1
    kind: L2Advertisement
    metadata:
      name: pools-advertisement
      namespace: {{ .Values.namespaceOverride }}
      annotations:
        helm.sh/hook: post-install
    spec:
      ipAddressPools:
        {{- range .Values.ipAddressPools }}
        - {{ .name }}
        {{ end -}}
